### ISSUE TITLE
What do the values in @include ms-respond(font-size, 0); mean?

### ISSUE THREAD

**Issue by christiantype** [modularscale/modularscale-sass#121]
I'm working on implementing the ms-ranges to my site. I set three three breakpoints:
desktop: 20em 
tablet: 40em
desktop: 64em

As noted on the ms repo, the `$ms-range` includes a ratio and breakpoint. 

Whichever ratio, I choose — what relationship does that ratio have to `$ms-ratio` that I use? 

For example:
If my  `$ms-ratio` is set to `$golden`, and I set my `$ms-range` to `1 20em, 1 40em, 1.333 64em;` then for the `20em` breakpoint, would the font-size be `ms(1)`?

This is what I have in my `style.scss` file.

```
.about h1 {
  clear:both;
  color:$midcolor;
  font-size:ms(1);
  font-weight: 400;
  @include ms-respond(font-size, 4);
}
```

As you can see, I have included `@include ms-respond(font-size, 4);`

The first value would be`font-size:ms(1);`, correct? and the `4` would be derived from the `ms-range?`

> The second value is the point on the scale you wish to use.

How do I know what points on the scale are available to know where to choose from?

**Comment by scottkellum** [comment]
Thanks @christiantype this gives me much more understanding into what you are trying to do.

First, lets get ranges sorted out. You only need to use breakpoints where a change happens, for example if you only want changes to take place at `40em` and `64em` then you only need to define those two points.

There is also no relationship between your default ratio and the ratio defined in your range unless you wish to make that connection. That said, your ratio _must be greater than 1_ so values of `1` may result in errors. Here is an example of a rage where it starts at a ratio of `1.333` and goes up to your default ratio:

``` scss
$ms-range:
  1.333 40em,
  $ms-ratio 64em;
```

Note the ratios here are all above `1` because a ratio of `1` doesn’t result in a modular scale. (anything multiplied by 1 = itself).

Now that we have set up a range, lets look at our mixin. But first to understand it, lets look at how the function is used, say I want to define my `h1` font size:

``` scss
h1 {
  font-size: ms(4);
}
```

Sass functions can only write _values_ but for this to be responsive we are going to need a series of breakpoints, properties, and values. So for the above value to follow our responsive ranges we set up you would write it like this:

``` scss
h1 {
  @include ms-respond(font-size, 4);
}
```

So at the breakpoint of `40em` the above code would pull the 4th value on your type scale with a ratio of `1.333` and at a breakpoint of `64em` the font size would also be the 4th value on your type scale but with your default ratio. So both values would be `ms(4)` and the ratio would change based on the range. This results in higher contrast between large and small text sizes on large screens.

**Comment by scottkellum** [comment]
Let me know if that worked @christiantype so I can resolve this issue.

**Comment by christiantype** [comment]
@scottkellum, thanks for the explanation.

So there is no need to use both   `font-size: ms(4);` and   `@include ms-respond(font-size, 4);
` to define, let's say a `h1`? The `font size` value in `ms-respond` is simply there to indicate that font-size is what is changed, correct?

Also, let's say I have a `p` that has `font-size:ms(0);` and when viewport falls below `64em`, how can I have that `p` for instance have `font-size:ms(-1)`. If the range has to be greater than 1, does that mean I can never have a range go below the `$ms-base`? I suppose, if I want to use a smaller font-size, my best bet would just be to choose a different `$ms-ratio`? I think I answered my own question here. :blush:

**Comment by scottkellum** [comment]
Hey, apologies for the delay.

> So there is no need to use both   `font-size: ms(4);` and   `@include ms-respond(font-size, 4);` to define, let's say a `h1`? The `font size` value in `ms-respond` is simply there to indicate that font-size is what is changed, correct?

Yup! that’s correct. You plug in the property you want to change (font-size) and ms value (value): `@include ms-respond(property, value);`.

> Also, let's say I have a `p` that has `font-size:ms(0);` and when viewport falls below `64em`, how can I have that `p` for instance have `font-size:ms(-1)`. If the range has to be greater than 1, does that mean I can never have a range go below the `$ms-base`? I suppose, if I want to use a smaller font-size, my best bet would just be to choose a different `$ms-ratio`? I think I answered my own question here. :blush:

The value in the `ms()` function is not tied to range at all. Only the ratio and breakpoint are effected by your range. The `ms()` value is the location on your scale and the responsive scale is designed to keep relationships between values the same while ratios may change across breakpoints. If you wish to change the relationship between breakpoints you can do that by explicitly defining what values you want at different breakpoints by using media queries and the standard `ms()` function.

**Comment by scottkellum** [comment]
@christiantype I’m gonna close this issue if you’re all set now.

**Comment by christiantype** [comment]
@scottkellum, sorry for the late reply. All is good. Thanks for helping out.

**Comment by ghetolay** [comment]
I think something like [this comment](https://github.com/modularscale/modularscale-sass/issues/121#issuecomment-202464919) could be part of the readme or some docs.

I had trouble to understand ms-respond() but now it's clear so those explanations should be more visible.
