### ISSUE TITLE
Pixel Rounding

### ISSUE THREAD

**Issue by OllieBrkr** [modularscale/modularscale-sass#132]
Is there a reason why we're rounding to whole pixel values (`_round-px.scss`)?

To be it seems contradictory to using a modular scale in the first place. From some basic checking it doesn't seem like Chrome, Firefox or Safari will round values automatically so I can't see it being a consistency issue.

Is there something I'm missing? Would love some clarification on this. Thanks!

**Comment by scottkellum** [comment]
Hey @OllieBrkr it helps keep output as minimal as it needs to be. For 2x screens I can see some advantages of rounding to `.5` instead of whole numbers but the irregularity across all devices makes me think rounding to the nearest pixel, as the smallest consistent unit on all devices, is appropriate.

I tend to recommend using modular scale with em or rem as the relativity of those units tends to work best with how scales work

**Comment by OllieBrkr** [comment]
Hey @scottkellum, thanks for the fast response :)

Makes sense to me. Just makes me a little sad how specific modular-scale lets us be in terms of how fonts relate to each other, yet rounding them removes a fair amount of that accuracy.

**Comment by scottkellum** [comment]
Yeah I get that, it’s kinda false accuracy though as browsers do the rounding anyway.
