### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by JoeCianflone** [modularscale/modularscale-sass#14]
Wondering if this is dead because there seem to be a couple of issues and no work as been done on this project
1.  There is no scss file
2.  There is no template folder so nothing gets copied into your project

**Comment by scottkellum** [comment]
Not dead, just kind of done.

1) We had both Sass and SCSS originally but @canarymason and myself prefer the Sass syntax. There are some issues when including both files in Compass so I removed SCSS.

2) You will need to explicitly include modular-scale yourself in projects.

On the issue of being “done” we will update it when new features to Sass/Compass are introduced that will make this better. If exponents, list ordering, and other features are added we will update to support those features. I have been thinking about switching the $base-size variable to 16px instead of 14 px. If @canarymason or I, or any one else who submits a pull request to refactor or make this better then we will happily update the project.

Are you having any issues with this project we can help you with? Are you interested in contributing to it?

**Comment by JoeCianflone** [comment]
Interested in contributing.  I resolved my issues by just pulling in the sass file.  I'll see what I can do this and next and send you guys a pull request.  I had a couple of ideas that I think could be interesting, I'll send them as feature branches too.
