### ISSUE TITLE
modularscale with breakpoints generate the same values for each breakpoint

### ISSUE THREAD

**Issue by ligne13** [modularscale/modularscale-sass#143]
Hi,

I have this setup :
```
$font-size-base: 16px;
$modularscale: (
  base: $font-size-base,
  ratio: 1.067,
  768px: (
    ratio: 1.125,
  ),
);
```

Then I use :
```
h1 {
  @include ms-respond(font-size, 12);
}
```

but the output CSS gives the same font-size value for the two breakpoints :
```
h1 {
  font-size:66px;
}
@media (min-width:768px){
  h1 {
    font-size:66px;
  }
}
```

Only the 1.125 ratio is used...

What am I doing wrong ?

thanks

**Comment by ligne13** [comment]
It seems that the ms-respond function does not work as expected if there are only 1 breakpoint defined in the $modularscale variable, like in my example.
Can you confirm / fix ?

thanks

**Comment by scottkellum** [comment]
@ligne13 Hey I’m running into a few problems implementing this.
1) Things are currently implemented in a way where the base is independent of the breakpoints meaning you don’t have to tie your base to a particular breakpoint. This is because ratios gain more meaning at larger breakpoints so the default often doesn’t make sense as the first breakpoint.
2) The code doesn’t know ahead of time how many breakpoints will be used and changing this has been more difficult than expected. I would need to do this to add conditional logic if there is only one breakpoint defined.

I’ve been toying with the idea of adding a variable to allow for non-fluid breakpoints that when toggled would cut things into distinct areas. However this changes the behavior more than I would like.

I initially designed this feature to push people to use fluid scales as opposed stepped breakpoints, especially as stepped breakpoints are straightforward to implement within whatever system you are already using to define them. I’m still pondering what the best path is forward for this issue in Modular Scale, but I recommend calling your breakpoint as you normally would and then calling the scale you would like to use like so:

```
h1 {
  font-size: ms(12);
  @media (min-width: 768px) {
    font-size: ms(12, $thread: 768px);
  }
}
```

**Comment by wagonmonster** [comment]
HI, I'm having the same issue

**I have:**

$modularscale: (
  base: 18px,
  ratio: 1.2,
  425px: (
     base: 24px,
	 ratio: 1.33,
  ),
  2345px: (
    base: 30px,
    ratio: 1.6,
  ),
);

**Then**

$font-base:ms(0);

**And**

font-size:$font-base;

But, no matter what, I always get....

body {
    font-size: 18px;
}

Any updates?

**Comment by scottkellum** [comment]
Thanks @wagonmonster for the comment, It’s a slightly different issue but good news is I’ve got a solution for you!

Check out this pen: https://codepen.io/scottkellum/pen/2f9f05cf8d6b7aff551fcd72e78b2a0c?editors=0100

You need to use `@include ms-respond(font-size,0);` instead of using the `ms(0)` function and it’ll work for you.

**Comment by scottkellum** [comment]
I’m going to close this issue. I don’t plan on changing the behavior.
