### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by davidhellmann** [modularscale/modularscale-sass#152]
```
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("ln-maclaurin")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("exp-maclaurin")) instead.
```

can u fix that? :)

![image](https://user-images.githubusercontent.com/764292/40484314-7285d9d4-5f5b-11e8-8eca-49482d9ffece.png)

**Comment by scottkellum** [comment]
Thanks for the issue! I’ll look into this later

**Comment by scottkellum** [comment]
@davidhellmann Can you isolate this to this plugin? I’m unable to replicate it. It could be an issue with how exponents are implemented via mathsass or similar.

**Comment by davidhellmann** [comment]
it’s within the pow.scss 
i am at holidays at the moment and i have just my iphone with me.

**Comment by scottkellum** [comment]
@davidhellmann What environment are you in and are you running any other plugins?

Also take your time and enjoy your holiday!

**Comment by davidhellmann** [comment]
I use it within my boilerplate: http://baukasten.io and yes. other plugins are installed but no one uses the pow function

**Comment by scottkellum** [comment]
@davidhellmann Thanks! It looks like your issue is here: https://github.com/davidhellmann/generator-baukasten/blob/master/generators/app/templates/___src/assets/css/______tools/_tools.function.pow.scss#L45

Modular scale looks for existing exponent logic and piggy backs on that. This allows people to use non-integer values in their scales IF they have support without overcomplicating the codebase for those who don’t need this feature. There are also ways of implementing exponents in Ruby on Ruby Sass instead of writing them in Sass allowing for dramatic performance gains so leveraging whatever pow function people have is often the most optimal solution.

Hopefully this helps!

**Comment by davidhellmann** [comment]
Hm, looks like u are right. Shame on me!

**Comment by scottkellum** [comment]
no worries glad we found it!
