### ISSUE TITLE
Choking on $golden variable

### ISSUE THREAD

**Issue by hatefulcrawdad** [modularscale/modularscale-sass#22]
Hey Scott,

We're using Modular Scale in Foundation 3 and I'm having a difficult time getting the $ratio variable to change correctly. You can see how we're using it here: https://github.com/zurb/foundation/tree/master/stylesheets/foundation

The problem is when people create a new compass project and update the ratio, it doesn't change. I've tried moving variable order around and commenting/uncommenting from within modular-scale.sass. Can you take a look at our repo and see if we're doing something wrong? 

If there is any other information I should pass along, let me know.

**Comment by scottkellum** [comment]
I noticed you removed the default from the modular scale partial and moved it to settings. This is good as you don’t want two $ratio variables with !default.

In a brief glance it doesn’t look like you have other conflicts with this variable. You are defining one default in the stylesheets and one override avalible in the template.

I do recommend calling settings before any other partial, looks like settings is after Compass and modular scale.

Also, @canarymason is working on a major re-write in Ruby. I hope to dig into it once I have time to get some basic Ruby concepts under my belt but when the update goes through you should consider including the gem as a dependency instead of copy/pasted in.

**Comment by hatefulcrawdad** [comment]
The problem with putting settings above modular scale is that no variable called `$golden` has been defined at that point so it trips up. I had everything fine and dandy without throwing errors, but when I updated `$golden` to `$octave` or anything else, it didn't change anything in the stylesheets.

**Comment by scottkellum** [comment]
Ahhh, you are right on the order. I will try to isolate this when I have some time later.

**Comment by scottkellum** [comment]
I am still unable to replicate this bug even when copy/pasting the slightly modified modular scale from @zurb source. Switching ratios in user styles seems to work fine. If you can isolate further and find it is still an issue with modular scale please let us know and we will re-open this ticket.

Code in my local stylesheet:

``` sass
@import "../../stylesheets/modular-scale"

$ratio: $fourth
$base-size: 1em

+modular-scale-list
```
