### ISSUE TITLE
variable issues in 2.0

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#63]
@scottkellum sorry for the delayed answer but i had no access to my computer the last week and had to leave in more or less of a hurry so i had no Github login credentials on my comp nor it would have helped since i would have been unable to test things. 

Did that now with Alpha 2 finally but i get:

```
error style.scss (Line 4 of _modular-scale.scss: Undefined variable: "$major-third".)
```

It is error'ing more or less on the first occurrence of a scale variable: 

```
$base-size: 20px 44px;
$ratio: $major-third $fifth;
```

The whole thing seems somehow buggered. But Modular Scale is required and imported properly before. Real strange. :/ 

Shall i create a separate issue in the tracker here?

**Comment by scottkellum** [comment]
@rpkoller I had an error in alpha2 that I fixed in alpha3, so you need to update. With the latest pre release of Sass 3.3 and Compass this should work and return `61.03516px`:

``` SCSS
@import "modular-scale";

$ms-base: 20px 44px;
$ms-ratio: $major-third $fifth;

@debug ms(12);
```

**Comment by rpkoller** [comment]
@scottkellum ufff somehow the whole thing is driving me crazy. i had the impression that somehow my installed gems were a bit buggy in combination. so i've cleaned everything and only installed the most basic setup necessary to follow your described steps for debuging: 

```
sudo gem install compass --pre
sudo gem install modular-scale --pre 
```

which lead to the following

```
*** LOCAL GEMS ***

chunky_png (1.2.9)
compass (1.0.0.alpha.17)
compass-core (1.0.0.alpha.16)
compass-import-once (1.0.2)
ffi (1.9.3)
fssm (0.2.10)
json (1.8.1)
listen (1.1.6)
modular-scale (2.0.0.alpha3)
multi_json (1.8.2)
rb-fsevent (0.9.3)
rb-inotify (0.9.3)
rb-kqueue (0.2.0)
sass (3.3.0.rc.2)
```

when i tried the code snippet everything worked fine: i've received 61.03516px for ms(12). But is there a way that the modular-scale alpha is also working with the present stable sass and compass versions or are the release candidate and alpha versions mandatory? 
I have the feeling that some version and dependency issues might have been the root of my problem in the first place. Cuz over the last month gems from team sass required step by step sass and compass pre release versions it seems (cuz after cleaning my gem folder and reinstall i was unable to install a few gems i had versions before with the stable sass 3.2.x and compass 0.12.2 versions - which i was unable to reinstall now, only with the present rc and alphas of sass and compass listed above). 
Guess a basic question in a separate issue would be more appropriate. At least at the moment i am quite confused and puzzled. Am using Codekit and basically only need breakpoint (past 2.07 requires the compass and sass pre versions), toolkit, modular scale and singularity as gems but somehow i am unable to install that setup properly (with only one compass version at least).

**Comment by scottkellum** [comment]
@rpkoller The pre release version of modular scale should work perfectly fine with libsass, stable channel Sass, and pre-release version of Sass.

You can download the latest 2.0 release and paste it into your project directly if you don’t want to deal with gem stuff: https://github.com/Team-Sass/modular-scale/releases/latest

Still under development but it works for me in tests in these environments. Lets keep tracking this issue here, modular scale 2 is designed to support as many versions of Sass as possible.

As for other team-sass projects it is incredibly difficult to support multiple versions at once. Sass 3.3 is going stable very soon and these projects need to support 3.3. Sadly this means killing off 3.2 compatibility in most cases.

**Comment by rpkoller** [comment]
@scottkellum i guess the reason why it hasn't worked before was more the combination of gems (and their beginning transition to Sass 3.3. and Compass 1.0) i've used on the stable sass/compass branch i suppose, since everything worked properly in the test case as i've posted in my last comment. 

And i completely understand the difficulty of the transition process  maintaining gems for the upcoming Sass and Compass versions . Shouldn't be any kind of criticism from my side at any point, don't get me wrong. I just try to figure out a way get the most necessary gems going again on a stable sass/compass foundation since it seems the Sass release candidate as well as the Compass alphas seem to trouble Codekit a bit.

So a last general question about - sorry - i don't wanna drift away too far from topic. Would the following make sense? Install Sass 3.2.x and Compass 0.12.2 and aside that all gems from team sass in the last versions with dependencies on the stable sass and compass versions. like breakpoint 2.0.7, modular scale 2.0 alpha…. the last none sass 3.3 and compass 1.0 dependent version of  toolkit would be 1.3.8 ? and what would be the last version of singularity, i am uncertain due to the lack of a changelog, is it 1.1.1 or 1.1.2?

**Comment by scottkellum** [comment]
Yeah, Sass 3.2.x and Compass 0.12.x go together and Sass 3.3.x and Compass 1.0.x go together. Can’t mix and match them.

Last version of Singularity [should be 1.1.1](http://rubygems.org/gems/singularitygs) but the latest should work in Sass 3.2.x + Compass 0.12.x. Singularity 1.2 is where the upgrade should take place. We need to get that changelog up soon…

No worries on anything, just trying to explain a little better instead of just shooting things down :)

Are we all good? Should I close this issue? Let me know if there is anything else I can help you with.

**Comment by rpkoller** [comment]
hmm i've installed breakpoint 2.07 and modular scale alpha 4 now alongside sass 3.2.13 and compass 0.12.2. and everything works fine in a stripped down testcase!

but i have two problems left. somehow singularity install depends on sassy-maps no matter if i try to install singularity 1.08 or 1.1.2. . i always get:

```
ERROR:  Error installing singularitygs:
    sassy-maps requires sass (~> 3.3.0.rc.2, runtime)
```

But i had Singularity installed before in that environment and it worked  :/ .and while trying to install latest toolkit i get: 

```
ERROR:  Error installing toolkit:
    sass requires listen (~> 1.1.0, runtime)
```

when trying to install listen i get: 

```
ERROR:  Error installing listen:
    celluloid requires Ruby version >= 1.9.2.
```

which is rather odd since i've already had installed toolkit on ruby 1.8.7 . quite odd. But are there versions of singularity and toolkit, like breakpoint 2.0.7, save to use with the stable old Sass and Compass versions?

**Comment by rpkoller** [comment]
Ok Singularity is working even that the install shows an sassy-maps dependency error, but Singularity is installed anyway and it seems properly working too. Strange but anyway. ;))) The only thing i haven't managed to get going again is Toolkit. :(

**Comment by scottkellum** [comment]
@rpkoller Please open up this issue on those repos so all maintainers can be aware of them.

**Comment by rpkoller** [comment]
@scottkellum True. That's the better way to deal with the remaining issues. Done, posted separate issues on each issue tracker. I guess the issue here could be closed then since things work fine with Modular Scale now thanks to your fixes and advice. :) Thanks again!
