### ISSUE TITLE
Y'all really have disappoint me...

### ISSUE THREAD

**Issue by r007** [modularscale/modularscale-sass#81]
I liked the old style with pixels, and now, instead of all these nice `12px 16px 21px 28px 38px 51px 67px 90px` I'm getting `1em 1.33333em 1.77778em 2.37037em 3.16049em` etc. The layout of my website is totally broken now. I don't want to rewrite tons of code just because someone decided that the dimensions in ems _would be better_. Instead, I opened the source code in hoping to find something like this: 

``` scss
$ms-use-em: true !default;
```

but found nothing.

So, I downgraded ms from version 2.x to 1.x and I plan to abandon the use in the future. I have only one question: why you did this?

**Comment by r007** [comment]
Okay, I found the problem. Should be:

``` scss
$ms-base: 12px;
```

instead of

``` scss
$ms-base: 12px !default;
```

Sorry, my bad.

**Comment by scottkellum** [comment]
@r007 In the future people might be more inclined to help if your tone were less accusatory and you actually titled the issue in a way that clearly outlines the issue. `Use px base instead of em` would have been much more appropriate. We have reasons for the change in our defaults.

Modular-scale has always been unit agnostic and will continue to be forever. You can plug in `12foobar` and it will calculate scales in `foobar`. We made `1em` the default value of `$ms-base` for two reasons. First, `em` compounding mirrors the scale that is used making nesting predictable and harmonious with the base value. Secondly, this tool is often used on type and we wanted to encourage best practices and use of relative units here. We did think about `rem` briefly but browser support just isn’t there and I like the way `em` compounds.

And with that, I am closing this out.

**Comment by mashcode** [comment]
+1 ;)
