### ISSUE TITLE
Is @modular-scale-classes included?

### ISSUE THREAD

**Issue by fchristant** [modularscale/modularscale-sass#99]
This article about modular scale....

http://thesassway.com/projects/modular-scale

...mentions a mixin @modular-scale-classes which supposedly generates classes. I have a working modular scale setup but it keeps telling me this mixin is undefined. I was wondering whether that is by design or whether I should look for issues in my setup specifically?

Whilst asking this question, I am hoping I can ask one more. Modular scale seems very useful for calculating values based on a ratio, yet I wonder how/if it can help to establish vertical rhythm, where not just the font-size needs to be in ratio, but also it's line-height and or padding. Any best practices for such advanced usage?

**Comment by scottkellum** [comment]
@fchristant Hey, this is a really old article and feature and it has been depreciated. I recommend going to [modularscale.com](http://modularscale.com/) if you want to find a list of values or write your own loop if you need to write classes with modular scales.

I’m among the mindset that attempting vertical rhythm is the road to madness, but working with the golden ratio and ems things will tend to fall into place due to properties of the golden ratio and how values relate to other values on the scale.

**Comment by fchristant** [comment]
@scottkellum Thanks, eventually I did write my own loop. It generates 10 precalculated classes on the golden ratio scale for font-sizes and bottom margins. I apply them in the markup based on gut feeling. I totally agree that vertical rhythm on the web just cannot be done, except for very trivial websites.

**Comment by mashcode** [comment]
The tyranny of the pixel. Early on it was vellum. Aesthetic choices are always normalizing.
- I concur on v-rhythm

Marc
